# Generated by Django 5.0.1 on 2024-01-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0002_pokemoncard_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
